const styles = {
    container: {
      background: 'linear-gradient(-45deg, #cce7ff, #b3d9ff, #e0f0ff, #cce7ff)',
      backgroundSize: '400% 400%',
      animation: 'bgAnimado 15s ease infinite',
      padding: '40px 20px',
      fontFamily: '"Segoe UI", sans-serif',
      fontSize: '18px',
      lineHeight: '1.8',
      color: '#333',
      textAlign: 'center' as const,
      position: 'relative' as const,
      overflow: 'hidden',
      minHeight: '100vh',
    },
    cartaCerrada: {
      backgroundColor: '#fff',
      padding: '40px',
      borderRadius: '16px',
      boxShadow: '0 4px 12px rgba(0, 0, 0, 0.15)',
      maxWidth: '400px',
      margin: '100px auto',
      textAlign: 'center' as const,
      animation: 'fadeIn 0.5s ease',
    },
    title: {
      fontSize: '32px',
      color: '#333',
      marginBottom: '30px',
    },
    paper: {
      backgroundColor: '#fff',
      padding: '40px',
      borderRadius: '16px',
      boxShadow: '0 4px 12px rgba(0, 0, 0, 0.15)',
      maxWidth: '800px',
      margin: '0 auto',
      marginTop: '30px',
      whiteSpace: 'pre-line',
      animation: 'fadeIn 0.5s ease',
      color: '#333',
    },
    text: {
      whiteSpace: 'pre-line' as const,
      fontSize: '18px',
      lineHeight: '1.8',
    },
    mainButton: {
      marginTop: '30px',
      fontSize: '18px',
      padding: '12px 24px',
      backgroundColor: 'hotpink',
      color: '#fff',
      border: 'none',
      borderRadius: '10px',
      cursor: 'pointer',
    },
    modalOverlay: {
      position: 'fixed' as const,
      top: 0,
      left: 0,
      width: '100vw',
      height: '100vh',
      backgroundColor: 'rgba(0,0,0,0.6)',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 9999,
    },
    modal: {
      backgroundColor: '#fff',
      padding: '30px',
      borderRadius: '12px',
      textAlign: 'center' as const,
      boxShadow: '0 0 15px rgba(0,0,0,0.3)',
      maxWidth: '300px',
      animation: 'fadeIn 0.4s ease',
    },
    modalButtons: {
      display: 'flex',
      justifyContent: 'space-around',
      marginTop: '20px',
    },
    yesButton: {
      fontSize: '16px',
      padding: '10px 20px',
      backgroundColor: 'mediumseagreen',
      color: '#fff',
      border: 'none',
      borderRadius: '8px',
      cursor: 'pointer',
    },
    noButton: {
      fontSize: '16px',
      padding: '10px 20px',
      backgroundColor: '#999',
      color: '#fff',
      border: 'none',
      borderRadius: '8px',
      cursor: 'pointer',
    },
  };
  
  export default styles;
  